apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: site-kube-news
          image: ltonza/kube-news:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgre"
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_PASSWORD
              value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kube-news
  ports:
    - port: 85
      targetPort: 8080
      #nodePort: 30001
  type: ClusterIP
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: kube-news-ingress
#  labels:
#    name: kube-news-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#spec:
#  tls:
#  - hosts:
#    - "ci.sytes.net"
#    secretName: "kube-news-tls"
#  rules:
#  - host: ci.sytes.net
#    http:
#      paths:
#      - pathType: Prefix
#        path: "/"
#        backend:
#          service:
#            name: kube-news
#            port: 
#              number: 80

